name: Publish create package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write  # for npm provenance

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies and Build
        run: |
          cd packages/create-enterprise-monorepo
          npm install
          npm run build

      - name: Publish to npm
        run: |
          cd packages/create-enterprise-monorepo
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
